# -*- coding:utf-8 -*-
PIC_CODE_EXPIRES_SECONDS=90#图片验证码
SMS_CODE_EXPIRES_SECONDS=300#手机验证码

# SMS_CODE_EXPIRES_SECONDS=300
SESSION_EXPIRES_SECONDS=72000#用户登录信息
REDIS_AREA_INFO_EXPIRES_SECONDES=86400 #区域信息
REDIS_HOUSE_INFO_EXPIRES_SECONDES=86400#房屋信息

INDEX_HOUSE_COUNT=5#index 房屋数量
INDEX_HOUSE_EXPIRES_SECONDS=86400#index 房屋信息
INDEX_AREA_EXPIRES_SECONDS=86400
HOUSE_LIST_PAGE_CAPACITY=4 #搜索每页的房屋数
REDIS_HOUSE_LIST_EXPIRES_SECONDS=86400 #搜索房屋信息



QINIU_URL_PREFIX="http://pi4ea5sky.bkt.clouddn.com/"
filename='FgJPq-27-xt2jVWPRjYUW-uolT9R'
pic='http://pi4ea5sky.bkt.clouddn.com/FqvstQm5eBJX5F1euFblMvvhzaz4'