# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20)),
                ('ggoods_info', models.CharField(max_length=100)),
                ('gimage', models.ImageField(upload_to='good_image/')),
                ('gweight', models.CharField(default='500g', max_length=10)),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gclick', models.IntegerField()),
                ('gintroduction', tinymce.models.HTMLField()),
                ('gstore', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=0)),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodstest.GoodCategoryInfo')),
            ],
        ),
    ]
