# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodstest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodCategoryInfo',
            new_name='CategoryInfo',
        ),
        migrations.AlterModelTable(
            name='categoryinfo',
            table='categoryinfo',
        ),
        migrations.AlterModelTable(
            name='goodsinfo',
            table='goodsinfo',
        ),
    ]
