# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0005_auto_20181024_1708'),
        ('goodstest', '0003_auto_20181019_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('likenum', models.IntegerField()),
                ('dislikenum', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodstest.GoodsInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usertest.UserInfo')),
            ],
        ),
    ]
