# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodstest', '0004_commentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='dislikenum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='likenum',
            field=models.IntegerField(default=0),
        ),
    ]
