# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goodstest', '0006_commentinfo_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gclick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gintroduction',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
