# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 06:23
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goodstest', '0008_auto_20181029_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gintroduction',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
