# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=30)),
                ('aParea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usertest.AreaInfo')),
            ],
            options={
                'db_table': 'areainfo',
            },
        ),
        migrations.CreateModel(
            name='UserAddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another_name', models.CharField(max_length=20)),
                ('urecipients', models.CharField(max_length=20)),
                ('upro', models.IntegerField(default=0)),
                ('ucity', models.IntegerField(default=0)),
                ('udisc', models.IntegerField(default=0)),
                ('uaddress', models.CharField(max_length=80)),
                ('upostcode', models.CharField(max_length=6)),
                ('uaddphone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'useraddressinfo',
            },
            managers=[
                ('useraddress', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=40)),
                ('umail', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'userinfo',
            },
            managers=[
                ('user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='useraddressinfo',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usertest.UserInfo'),
        ),
    ]
