# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0002_userinfo_default_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='goodsids',
            field=models.CommaSeparatedIntegerField(default=0, max_length=5),
        ),
    ]
