# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0003_userinfo_goodsids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='goodsids',
            field=models.CommaSeparatedIntegerField(default=0, max_length=40),
        ),
    ]
