# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0004_auto_20181024_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='goodsids',
            field=models.CommaSeparatedIntegerField(default='', max_length=40),
        ),
    ]
