# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usertest', '0002_userinfo_default_id'),
        ('goodstest', '0003_auto_20181019_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='goodstest.GoodsInfo')),
            ],
            options={
                'db_table': 'orderdetailinfo',
            },
            managers=[
                ('orderdetail', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('odate', models.DateTimeField(auto_now=True)),
                ('statu', models.BooleanField()),
                ('oaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usertest.UserAddressInfo')),
                ('ouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usertest.UserInfo')),
            ],
            options={
                'db_table': 'orderinfo',
            },
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordertest.OrderInfo'),
        ),
    ]
