# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertest', '0002_auto_20181023_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='omoney',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
