# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertest', '0003_orderinfo_omoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='statu',
            field=models.IntegerField(),
        ),
    ]
