# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carttest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartinfo',
            table='cartinfo',
        ),
    ]
